sign_h:
  WRJ1: -0.479142
  WRJ0: -0.074899
  FFJ3: -0.314156
  FFJ2: 0.009370
  FFJ1: 0.009529
  FFJ0: 0.009936
  MFJ3: -0.339316
  MFJ2: 0.009366
  MFJ1: 0.009527
  MFJ0: 0.009936
  RFJ3: -0.339330
  RFJ2: 1.561402
  RFJ1: 1.498437
  RFJ0: 1.562331
  LFJ4: 0.173831
  LFJ3: -0.339340
  LFJ2: 1.561438
  LFJ1: 1.498420
  LFJ0: 1.562324
  THJ4: 0.722387
  THJ3: 1.073435
  THJ2: 0.199362
  THJ1: -0.499172
  THJ0: -1.561071