a: 
  sign:
    WRJ1: -0.000000
    WRJ0: -0.066764
    FFJ3: 0.000000
    FFJ2: 1.561403
    FFJ1: 0.885386
    FFJ0: 1.152955
    MFJ3: 0.000000
    MFJ2: 1.561407
    MFJ1: 0.995356
    MFJ0: 1.278506
    RFJ3: 0.000000
    RFJ2: 1.561407
    RFJ1: 1.042394
    RFJ0: 1.332207
    LFJ4: 0.073789
    LFJ3: -0.000256
    LFJ2: 1.561423
    LFJ1: 1.034548
    LFJ0: 1.323245
    THJ4: 0.059405
    THJ3: 0.493136
    THJ2: 0.199144
    THJ1: -0.514447
    THJ0: -0.456980
  action: [
    0.555, 
    0.176, 
    0.000, 
    1.000, 
    0.120, 
    0.000, 
    1.000, 
    0.260, 
    0.000, 
    1.000, 
    0.320, 
    -0.740, 
    0.000, 
    1.000, 
    0.310, 
    0.050, 
    -0.160, 
    1.000, 
    -1.000, 
    0.420
  ]
