i:
  sign:
    WRJ1: -0.237400
    WRJ0: -0.070613
    FFJ3: 0.000000
    FFJ2: 1.561399
    FFJ1: 1.498428
    FFJ0: 1.562330
    MFJ3: 0.002116
    MFJ2: 1.561171
    MFJ1: 1.499321
    MFJ0: 1.562497
    RFJ3: 0.000000
    RFJ2: 1.561402
    RFJ1: 1.498437
    RFJ0: 1.562331
    LFJ4: 0.009137
    LFJ3: 0.000136
    LFJ2: 0.009362
    LFJ1: 0.009526
    LFJ0: 0.009936
    THJ4: 0.419010
    THJ3: 1.154544
    THJ2: 0.199643
    THJ1: -0.266863
    THJ0: -1.088588
  action: [
    -0.200, 
    0.176, 
    0.000, 
    1.000, 
    1.000, 
    0.000, 
    1.000, 
    1.000, 
    0.000, 
    1.000, 
    1.000, 
    -1.000, 
    0.000, 
    -1.000, 
    -1.000, 
    0.460, 
    0.830, 
    1.000, 
    -0.590, 
    -0.410
  ]