l:
  sign:
    WRJ1: -0.000000
    WRJ0: -0.070076
    FFJ3: -0.000000
    FFJ2: 0.009367
    FFJ1: 0.009529
    FFJ0: 0.009936
    MFJ3: 0.000000
    MFJ2: 1.561402
    MFJ1: 1.498437
    MFJ0: 1.562331
    RFJ3: 0.000000
    RFJ2: 1.561402
    RFJ1: 1.498437
    RFJ0: 1.562331
    LFJ4: 0.009268
    LFJ3: -0.000029
    LFJ2: 1.561407
    LFJ1: 1.498439
    LFJ0: 1.562331
    THJ4: -0.004823
    THJ3: 0.009317
    THJ2: 0.199055
    THJ1: 0.514358
    THJ0: -0.009639
  action: [ 
    0.555, 
    0.176, 
    0.000, 
    -1.000, 
    -1.000, 
    0.000, 
    1.000, 
    1.000, 
    0.000, 
    1.000, 
    1.000, 
    -1.000, 
    0.000, 
    1.000, 
    1.000, 
    0.000, 
    -1.000, 
    1.000, 
    1.000, 
    1.000
  ]