r:
  sign:
    WRJ1: -0.000000
    WRJ0: -0.074235
    FFJ3: -0.165099
    FFJ2: 0.741008
    FFJ1: 0.009551
    FFJ0: 0.009950
    MFJ3: 0.317021
    MFJ2: 0.009179
    MFJ1: 0.009527
    MFJ0: 0.009936
    RFJ3: -0.339314
    RFJ2: 1.557509
    RFJ1: 1.498437
    RFJ0: 1.562332
    LFJ4: 0.213251
    LFJ3: -0.339351
    LFJ2: 1.561647
    LFJ1: 1.498414
    LFJ0: 1.562323
    THJ4: 0.718737
    THJ3: 1.071983
    THJ2: 0.199356
    THJ1: -0.503844
    THJ0: -1.561128
  action: [
    0.555, 
    0.176, 
    -0.540, 
    -0.070, 
    -1.000, 
    1.000, 
    -1.000, 
    -1.000, 
    -1.000, 
    1.000, 
    1.000, 
    -0.360, 
    -1.000, 
    1.000, 
    1.000, 
    0.710, 
    0.750, 
    1.000, 
    -1.000, 
    -1.000
  ]
