# Default settings
defaults:
  - _self_
  - hydra: local
  - sites/fingertip
  - sites/target
  - sites/finger
  - goal/medium

# MuJoCo camera settings 
camera:
  distance: 0.5
  azimuth: 0.0
  elevation: -25.0
  lookat: [1, 0.96, 0.14]
  width: 256
  height: 256

# Scene path 
scene_path: "../assets/hand/reach.xml"

# Distance reward weight
distance_weight: 10.0